
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gmp-test
  labels:
    app.kubernetes.io/name: flask-app
  name: flask-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app

  replicas: 6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - image: gcr.io/certain-region-328814/gmp-sh/shrey-mng-prom-image
        name: flask-app
        ports:
        - name: metrics
          containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: gmp-test
spec:
  selector:
    app.kubernetes.io/name: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: metrics
  type: LoadBalancer