apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: flask-app
  labels:
    app.kubernetes.io/name: flask-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app
  endpoints:
  - port: metrics
    interval: 30s